version: '3.8'

networks:
  participe-ai:
    driver: bridge

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: development-stage
    container_name: frontend
    networks:
      - participe-ai
    ports:
      - "4200:4200"
    volumes:
      - ./frontend:/frontend
      - /frontend/node_modules
    
